name: iris_random_forest
description: Random Forest classifier for iris species prediction
version: 1.0

# Reference to feature set
feature_set: iris_features

# Target variable
target: species

# Features to use for training
features:
  # Original measurements
  - sepal_length
  - sepal_width
  - petal_length
  - petal_width
  # Engineered features
  - sepal_ratio
  - petal_ratio
  - sepal_area
  - petal_area
  - total_length
  - total_width
  - sepal_petal_length_ratio
  - sepal_petal_width_ratio

# Model configuration
model:
  type: sklearn
  class: ensemble.RandomForestClassifier
  hyperparameters:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 5
    min_samples_leaf: 2
    random_state: 42
    n_jobs: -1

# Train/test split strategy
split:
  method: random
  test_size: 0.3
  random_state: 42

# Evaluation metrics
metrics:
  - accuracy
  - f1
  - roc_auc

# Cross-validation
cross_validation:
  enabled: true
  n_folds: 5
  random_state: 42
