name: iris_features
description: Engineered features for iris classification
version: 1.0
dataset: iris_clean  # Reference the cleaned dataset

# Include source columns
include_source_columns: true

# Computed features
features:
  # Ratios between measurements
  - name: sepal_ratio
    expression: "sepal_length / sepal_width"
    description: "Ratio of sepal length to width"

  - name: petal_ratio
    expression: "petal_length / petal_width"
    description: "Ratio of petal length to width"

  # Area estimates (assuming elliptical shape)
  - name: sepal_area
    expression: "3.14159 * (sepal_length / 2) * (sepal_width / 2)"
    description: "Approximate sepal area"

  - name: petal_area
    expression: "3.14159 * (petal_length / 2) * (petal_width / 2)"
    description: "Approximate petal area"

  # Total size features
  - name: total_length
    expression: "sepal_length + petal_length"
    description: "Combined length of sepal and petal"

  - name: total_width
    expression: "sepal_width + petal_width"
    description: "Combined width of sepal and petal"

  # Interaction features
  - name: sepal_petal_length_ratio
    expression: "sepal_length / petal_length"
    description: "Ratio of sepal to petal length"

  - name: sepal_petal_width_ratio
    expression: "sepal_width / petal_width"
    description: "Ratio of sepal to petal width"

  # Size category (for demonstration)
  - name: size_category
    expression: |
      CASE
        WHEN petal_length < 2.0 THEN 'small'
        WHEN petal_length < 5.0 THEN 'medium'
        ELSE 'large'
      END
    description: "Size category based on petal length"

  # Species encoding (one-hot style indicators)
  - name: is_setosa
    expression: "CASE WHEN species = 'setosa' THEN 1 ELSE 0 END"
    description: "Binary indicator for setosa"

  - name: is_versicolor
    expression: "CASE WHEN species = 'versicolor' THEN 1 ELSE 0 END"
    description: "Binary indicator for versicolor"

  - name: is_virginica
    expression: "CASE WHEN species = 'virginica' THEN 1 ELSE 0 END"
    description: "Binary indicator for virginica"

# Window features (statistical rankings)
window_features:
  # Rank flowers by petal length within each species
  - name: petal_length_rank
    function: RANK
    partition_by: [species]
    order_by: [petal_length DESC]

  # Calculate z-score style features
  - name: sepal_length_zscore
    function: AVG
    column: sepal_length
    partition_by: [species]

# Quality filters on engineered features
filters:
  - column: sepal_ratio
    operator: ">"
    value: 0

  - column: petal_ratio
    operator: ">"
    value: 0
